# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
# GoReleaser 配置文件，用于自动构建和发布 Crush 项目
version: 2

project_name: crush  # 项目名称

includes:
  - from_url:
      url: purpose168/meta-cn/main/notarize.yaml  # 包含外部配置文件，用于应用程序签名

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"  # 模块时间戳，使用提交时间
  license: "FSL-1.1-MIT"  # 许可证类型
  homepage: "https://charm.sh/crush"  # 项目主页
  description: "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."  # 项目描述
  full_description: "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."  # 项目完整描述
  maintainers:
    - "kujtimiihoxha <kujtim@charm.sh>"
    - "caarlos0 <carlos@charm.sh>" # for aur

nightly:
  publish_release: true  # 发布夜间版本
  keep_single_release: true  # 只保留一个夜间版本
  version_template: "{{ incminor .Version }}-nightly"  # 夜间版本的版本模板

snapshot:
  version_template: "0.0.0-{{ .Timestamp }}"  # 快照版本的版本模板

before:
  hooks:
    - go mod tidy  # 整理 Go 模块依赖
    - rm -rf completions  # 删除旧的补全文件
    - mkdir completions  # 创建补全文件目录
    - rm -rf manpages  # 删除旧的手册页
    - mkdir manpages  # 创建手册页目录
    - sh -c 'go run . completion bash >./completions/crush.bash'  # 生成 Bash 补全
    - sh -c 'go run . completion zsh >./completions/crush.zsh'  # 生成 Zsh 补全
    - sh -c 'go run . completion fish >./completions/crush.fish'  # 生成 Fish 补全
    - sh -c 'go run . man | gzip -c >./manpages/crush.1.gz'  # 生成压缩的手册页

# gomod:
#   proxy: true

builds:
  - env:
      - CGO_ENABLED=0  # 禁用 CGO
      - GOEXPERIMENT=greenteagc  # 启用 Go 实验性功能
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - android
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm
      - goos: android
        goarch: "386"
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X github.com/purpose168/crush-cn/internal/version.Version={{.Version}}  # 设置版本信息
    flags:
      - -trimpath  # 移除构建路径中的绝对路径

archives:
  - name_template: >-
      crush_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm}}v{{ . }}{{ end }}
    wrap_in_directory: true  # 将文件包装在目录中
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*
    format_overrides:
      - goos: windows
        formats: [zip]  # Windows 使用 zip 格式

checksum:
  name_template: "checksums.txt"  # 校验和文件名

aur_sources:
  - private_key: "{{ .Env.AUR_KEY }}"  # AUR 私钥
    disable: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时禁用
    git_url: "ssh://aur@aur.archlinux.org/crush.git"  # AUR 仓库 URL
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"
    makedepends:
      - go
      - git
    prepare: |-
      go mod download  # 下载依赖
    build: |-
      mkdir completions
      mkdir manpages
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build -ldflags="-w -s -buildid='' -linkmode=external -X github.com/purpose168/crush-cn/internal/version.Version=v${pkgver}" .
      ./crush completion bash >./completions/crush.bash
      ./crush completion zsh >./completions/crush.zsh
      ./crush completion fish >./completions/crush.fish
      ./crush man | gzip -c >./manpages/crush.1.gz
    package: |-
      # bin
      install -Dm755 "./crush" "${pkgdir}/usr/bin/crush"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/crush/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/crush/"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/crush.bash" "${pkgdir}/usr/share/bash-completion/completions/crush"
      install -Dm644 "./completions/crush.zsh" "${pkgdir}/usr/share/zsh/site-functions/_crush"
      install -Dm644 "./completions/crush.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/crush.fish"
      # man pages
      install -Dm644 "./manpages/crush.1.gz" "${pkgdir}/usr/share/man/man1/crush.1.gz"
      # readme
      mkdir -pv "${pkgdir}/usr/share/doc/crush/"
      install -Dm644 README* "${pkgdir}/usr/share/doc/crush/"

aurs:
  - private_key: "{{ .Env.AUR_KEY }}"  # AUR 私钥
    disable: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时禁用
    git_url: "ssh://aur@aur.archlinux.org/crush-bin.git"  # AUR 二进制包仓库 URL
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"
    provides:
      - crush
    conflicts:
      - crush
    package: |-
      case "$CARCH" in
        aarch64)
          cd "${srcdir}/crush_${pkgver}_Linux_arm64"
          ;;
        *)
          cd "${srcdir}/crush_${pkgver}_Linux_${CARCH}"
          ;;
      esac
      # bin
      install -Dm755 "./crush" "${pkgdir}/usr/bin/crush"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/crush/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/crush/"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/crush.bash" "${pkgdir}/usr/share/bash-completion/completions/crush"
      install -Dm644 "./completions/crush.zsh" "${pkgdir}/usr/share/zsh/site-functions/_crush"
      install -Dm644 "./completions/crush.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/crush.fish"
      # man pages
      install -Dm644 "./manpages/crush.1.gz" "${pkgdir}/usr/share/man/man1/crush.1.gz"
      # readme
      mkdir -pv "${pkgdir}/usr/share/doc/crush/"
      install -Dm644 README* "${pkgdir}/usr/share/doc/crush/"

furies:
  - disable: "{{ if (or .Prerelease .IsNightly) }}true{{ end }}"  # 预发布和夜间版本时禁用
    account: "{{ with .Env.FURY_TOKEN }}charmcli{{ else }}{{ end }}"  # Fury 账户
    secret_name: FURY_TOKEN  # Fury 令牌

brews:
  - repository:
      owner: charmbracelet
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  # GitHub 令牌
    skip_upload: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时跳过上传
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"
    goarm: 7
    extra_install: |-
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
      man1.install "manpages/{{ .ProjectName }}.1.gz"

scoops:
  - repository:
      owner: charmbracelet
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  # GitHub 令牌
    skip_upload: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时跳过上传
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"

npms:
  - name: "@charmland/crush"  # NPM 包名
    repository: "git+https://github.com/purpose168/crush-cn.git"  # 仓库 URL
    bugs: https://github.com/purpose168/crush-cn/issues  # Bug 报告 URL
    access: public  # 公开访问
    disable: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时禁用

nfpms:
  - formats:
      - apk
      - deb
      - rpm
      - archlinux
      - termux.deb
    file_name_template: "{{ .ConventionalFileName }}"  # 文件名模板
    contents:
      - src: ./completions/crush.bash
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files/usr{{ end }}/etc/bash_completion.d/crush'
      - src: ./completions/crush.fish
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/fish/vendor_completions.d/crush.fish'
      - src: ./completions/crush.zsh
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/zsh/site-functions/_crush'
      - src: ./manpages/crush.1.gz
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/man/man1/crush.1.gz'
    rpm:
      signature:
        key_file: '{{ if ne (index .Env "GPG_KEY_PATH") "" }}{{ .Env.GPG_KEY_PATH }}{{ else }}{{ end }}'  # GPG 密钥文件
    deb:
      signature:
        key_file: '{{ if ne (index .Env "GPG_KEY_PATH") "" }}{{ .Env.GPG_KEY_PATH }}{{ else }}{{ end }}'  # GPG 密钥文件

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"  # 签名文件
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum  # 对校验和文件进行签名
    output: true

source:
  enabled: true  # 启用源码发布

sboms:
  - artifacts: archive  # 为归档生成 SBOM
  - id: source
    artifacts: source  # 为源码生成 SBOM

nix:
  - repository:
      owner: "charmbracelet"
      name: nur
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  # GitHub 令牌
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"
    license: fsl11Mit  # 许可证
    formatter: nixfmt  # Nix 格式化工具
    skip_upload: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时跳过上传
    extra_install: |-
      installManPage ./manpages/crush.1.gz
      installShellCompletion ./completions/*

winget:
  - publisher: charmbracelet
    copyright: Charmbracelet, Inc
    publisher_url: https://charm.land
    release_notes_url: "https://github.com/purpose168/crush-cn/releases/tag/{{.Tag}}"  # 发布说明 URL
    license_url: https://github.com/purpose168/crush-cn/blob/main/LICENSE.md  # 许可证 URL
    skip_upload: "{{ with .Prerelease }}true{{ end }}"  # 预发布版本时跳过上传
    commit_author:
      name: "Charm"
      email: "charmcli@users.noreply.github.com"
    repository:
      owner: "charmbracelet"
      name: winget-pkgs
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  # GitHub 令牌
      branch: "crush-{{.Version}}"  # 分支名
      pull_request:
        enabled: true
        draft: false
        check_boxes: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

changelog:
  sort: asc  # 按升序排序
  disable: "{{ .IsNightly }}"  # 夜间版本时禁用
  use: github  # 使用 GitHub 变更日志
  filters:
    exclude:
      - "^(build|ci): "
      - "^chore: auto-update generated files$"
      - "^chore: docs$"
      - "^chore: schema update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: update schema$"
      - "^chore: update$"
      - "^chore\\(legal\\): "
      - "^chore\\(deps\\): "
      - "^docs: update$"
      - "^test:"
      - "^test\\("
      - "^v\\d.*"
      - "merge conflict"
      - "merge conflict"
      - Merge branch
      - Merge pull request
      - Merge remote-tracking branch
      - go mod tidy
      - "^wip "
      - "^wip:"
  groups:
    - title: "Deps"
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New!"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Fixed"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "Other stuff"
      order: 9999

release:
  prerelease: auto  # 自动检测预发布版本
  footer:
    from_url:
      url: https://raw.githubusercontent.com/purpose168/meta-cn/main/footer.md  # 页脚内容
